package com.lovigin.app.skillify

object Const {
    val icons = mapOf(
        "Graphic Design" to "🎨",
        "Photography" to "📷",
        "Web Design" to "💻",
        "Cooking" to "🍴",
        "Programming" to "💻",
        "Fitness" to "🏋️",
        "Yoga" to "🧘",
        "Sewing" to "✂️",
        "Dancing" to "💃",
        "Painting" to "🖌️",
        "Financial" to "💵",
        "Marketing" to "📢",
        "Development" to "🧠",
        "Psychology" to "💓",
        "Sociology" to "👥",
        "Writing" to "✏️",
        "Public Speaking" to "🎙️",
        "Project Management" to "📊",
        "Entrepreneurship" to "💼",
        "Gardening" to "🌿",
        "Self-Defense" to "🛡️",
        "Knitting" to "🧶",
        "Jewelry Making" to "💍",
        "Meditation" to "🙌",
        "Astronomy" to "🔭",
        "Karate" to "🥋",
        "Boxing" to "🥊",
        "Ballet" to "🩰",
        "Salsa" to "💃",
        "Singing" to "🎤",
        "Music Recording" to "🎤",
        "Video Creation" to "📹",
        "Drum Playing" to "🥁",
        "Violin Playing" to "🎻",
        "Piano Playing" to "🎹",
        "Manicure" to "💅",
        "Makeup" to "💄",
        "Running" to "🏃",
        "Cycling" to "🚴",
        "Swimming" to "🏊",
        "Tennis" to "🎾",
        "Chess" to "♟️",
        "Golf" to "⛳",
        "Surfing" to "🏄",
        "Sailing" to "⛵",
        "Drawing" to "✏️",
        "Sculpture" to "🔨",
        "Calligraphy" to "✒️",
        "Comedy" to "🎭",
        "Blogging" to "✍️",
        "SEO" to "🔍",
        "Social Media Management" to "👤",
        "Mobile Photography" to "📱",
        "Digital Art" to "🖥️",
        "Juggling" to "🤹",
        "Magic" to "🪄",
        "Political Science" to "🏛️",
        "Electronics" to "🔌",
        "Automotive" to "🚗",
        "Music" to "🎵",
        "Guitar" to "🎸",
        "Sports" to "⚽",
        "Languages" to "📚",
        "Graffiti" to "💭",
        "Fishing" to "🎣",
        "Modeling" to "🧊",
        "Accounting" to "🧮",
        "Ceramics" to "🍶",
        "Acting" to "🎭",
        "Hiking" to "🥾",
        "Snowboarding" to "🏂",
        "Woodworking" to "🪚",
        "Robotics" to "🤖",
        "Physics" to "⚛️",
        "Skiing" to "⛷️",
        "Biology" to "🍃",
        "Chemistry" to "⚗️",
        "History" to "📚",
        "Mathematics" to "➕",
        "Literature" to "📚",
        "Philosophy" to "🧠",
        "Economics" to "⚖️",
        "Consulting" to "👤",
        "Startups" to "🚀"
    )
}